/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Cristian
 * Created: 9-mag-2017 
 */
-- USERNAME: cri--
-- PASSWORD: 123-- 


CREATE TABLE utenti(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(256) UNIQUE,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    urlfotoprofilo VARCHAR(256),
    presentazione VARCHAR(256),
    datanascita DATE,
    password VARCHAR(256)
);


CREATE TABLE post(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_post INTEGER,
    autore_post INTEGER,
    content VARCHAR(1024),
    FOREIGN KEY (utente_post) REFERENCES utenti(id),
    FOREIGN KEY (autore_post) REFERENCES utenti(id)
);

CREATE TABLE gruppi(
    gruppo_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_gruppo VARCHAR(256),
    data_creazione DATE,
    amm_gruppo INTEGER,
    FOREIGN KEY (amm_gruppo) REFERENCES utenti(id)
   
    
);

CREATE TABLE partecipa(
    utente_id INTEGER,
    gruppo_id INTEGER,
    FOREIGN KEY (utente_id) REFERENCES utenti(id),
    FOREIGN KEY (gruppo_id) REFERENCES gruppi(gruppo_id),
    PRIMARY KEY (utente_id, gruppo_id)
);

CREATE TABLE amicizia(
    utente INTEGER,
    seguace INTEGER,
    FOREIGN KEY (utente) REFERENCES utenti(id),
    FOREIGN KEY (seguace) REFERENCES utenti(id),
    PRIMARY KEY (utente,seguace)
);


CREATE TABLE post_gruppo(
    post_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gruppo_id INTEGER,
    autore_post_gruppo INTEGER,
    content VARCHAR(1024),
    FOREIGN KEY (autore_post_gruppo) REFERENCES utenti(id),
    FOREIGN KEY (gruppo_id) REFERENCES gruppi(gruppo_id)
);  

CREATE TABLE amm(
    utente INTEGER,
    FOREIGN KEY (utente) REFERENCES utenti(id),
    PRIMARY KEY (utente)
);
--Utenti--

INSERT INTO utenti (id, username, nome, cognome, urlfotoprofilo, presentazione, 
                    datanascita, password)
VALUES (default, 'cristiano', 'Cristian', 'Rossi', 'img/ginopino.jpg', 'Ciao Ciao', '12/30/1990', '12345678' );

INSERT INTO utenti (id, username, nome, cognome, urlfotoprofilo, presentazione, 
                    datanascita, password)
VALUES (default, 'gianino', 'Gianni', 'Bianchi', 'img/marioloco.jpg', 'Bye Bye', '12/09/1956', '2');

INSERT INTO utenti (id, username, nome, cognome, urlfotoprofilo, presentazione, 
                    datanascita, password)
VALUES (default, 'pino', 'daniele', 'Piccolo', 'img/marioloco.jpg', 'Ciao ciaone', '10/09/1986', '000000');

INSERT INTO utenti (id, username, nome, cognome, urlfotoprofilo, presentazione, 
                    datanascita, password)
VALUES (default, 'lola', 'Lolita', 'Bianchi', 'img/tinotoni.jpg', 'Bye Bye', '12/09/1956', '2');

-- Post --

INSERT INTO post (id, utente_post, autore_post, content)
VALUES (default, 1, 1, 'fsdsdfsdfsdfsdfsdfsd');

INSERT INTO post (id, utente_post, autore_post, content)
VALUES (default, 1, 3, 'rtsgfsdfsfsdfsdfsdfsdfsdfsdfsdfsdfsd');   

INSERT INTO post (id, utente_post, autore_post, content)
VALUES (default, 2, 2, 'fsdfsdfsdfsdfsdfsdfsdfsfsdfsd');

INSERT INTO post (id, utente_post, autore_post, content)
VALUES (default, 3, 4, 'dfgsdfsdfsdfsdfsdfsdfsdfsdfsdf');

INSERT INTO post (id, utente_post, autore_post, content)
VALUES (default, 4, 3, 'osizione fra t');


-- Amicizie --

INSERT INTO amicizia(utente, seguace)
VALUES (1,2);

INSERT INTO amicizia(utente, seguace)
VALUES (2,1);

INSERT INTO amicizia(utente, seguace)
VALUES (3,1),(3,4);

INSERT INTO amicizia(utente, seguace)
VALUES (4,3);

-- Gruppi --

INSERT INTO gruppi(gruppo_id, nome_gruppo, data_creazione, amm_gruppo)
VALUES (default, 'Musica', '09/09/2012',1);

INSERT INTO gruppi(gruppo_id, nome_gruppo, data_creazione, amm_gruppo)
VALUES (default, 'Giochi', '05/20/2009',3);

-- Partecipanti --

INSERT INTO partecipa(utente_id, gruppo_id)
VALUES (1,1),(2,1);

INSERT INTO partecipa(utente_id, gruppo_id)
VALUES (1,2),(3,2);

-- Posts gruppo --

INSERT INTO post_gruppo(post_id , gruppo_id, autore_post_gruppo, content)
VALUES (default, 1, 2, ' ciacascascascascacascascascsacascascascascas' );


INSERT INTO post_gruppo(post_id , gruppo_id, autore_post_gruppo, content)
VALUES (default, 2, 3, ' dadasdasdasdsadasdasdas' );


-- amministratore --

INSERT INTO amm(utente)
VALUES (1);