/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Cristian
 * Created: 9-mag-2017 
 */
-- USERNAME: cri--
-- PASSWORD: 123-- 


CREATE TABLE utenti(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(256) UNIQUE,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    urlfotoprofilo VARCHAR(256),
    presentazione VARCHAR(256),
    datanascita DATE,
    password VARCHAR(256)
);


CREATE TABLE post(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_post INTEGER,
    content VARCHAR(1024),
    FOREIGN KEY (utente_post) REFERENCES utenti(id)
);

CREATE TABLE gruppi(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_creazione DATE,
    utente_gruppo INTEGER,
    FOREIGN KEY (utente_gruppo) REFERENCES utenti(id)
);

CREATE TABLE partecipa(
    utente_id INTEGER,
    post_id INTEGER,
    FOREIGN KEY (utente_id) REFERENCES utenti(id),
    FOREIGN KEY (post_id) REFERENCES post(id)
);

--Utenti--

INSERT INTO utenti (id, username, nome, cognome, urlfotoprofilo, presentazione, 
                    datanascita, password)
VALUES (default, 'cri', 'Cristian', 'Rossi', 'img/ginopino.jpg', 'Ciao Ciao', '12/30/1990', '12345678' );

INSERT INTO utenti (id, username, nome, cognome, urlfotoprofilo, presentazione, 
                    datanascita, password)
VALUES (default, 'gianino', 'Gianni', 'Bianchi', 'img/marioloco.jpg', 'Bye Bye', '12/09/1956', '2');

INSERT INTO utenti (id, username, nome, cognome, urlfotoprofilo, presentazione, 
                    datanascita, password)
VALUES (default, 'pino', null, 'Piccolo', null, null, '10/09/1986', '000000');

INSERT INTO utenti (id, username, nome, cognome, urlfotoprofilo, presentazione, 
                    datanascita, password)
VALUES (default, 'lola', 'Lolita', 'Bianchi', 'img/tinotoni.jpg', 'Bye Bye', '12/09/1956', '2');

-- Post --

INSERT INTO post (id, utente_post, content)
VALUES (default, 1, 'fsdsdfsdfsdfsdfsdfsd');

INSERT INTO post (id, utente_post, content)
VALUES (default, 1, 'rtsgfsdfsfsdfsdfsdfsdfsdfsdfsdfsdfsd');   

INSERT INTO post (id, utente_post, content)
VALUES (default, 2, 'fsdfsdfsdfsdfsdfsdfsdfsfsdfsd');

INSERT INTO post (id, utente_post, content)
VALUES (default, 2, 'dfgsdfsdfsdfsdfsdfsdfsdfsdfsdf');

INSERT INTO post (id, utente_post, content)
VALUES (default, 4, 'Aristotile non si è acquistata sí grande autorità se non per la forza delle sue dimostrazioni e della profondità de i suoi discorsi: ma bisogna intenderlo, e non solamente intenderlo, ma aver tanta gran pratica ne suoi libri, che se ne sia formata unidea perfettissima modo che ogni suo detto vi sia sempre innanzi alla menteerché non ha scritto per il volgo, né si è obligato a infilzare i suoi silogismi col metodo triviale ordinato, anzi, servendosi del perturbato, ha messo talvolta la prova di una proposizione fra t');